# Programming for Data Analysis Assignment
### Assignment Outlines
The following assignment concerns the numpy.random package in Python 
1. Explain the overall purpose of the package. 
2. Explain the use of the “Simple random data” and “Permutations” functions. 
3. Explain the use and purpose of at least five “Distributions” functions. 
4. Explain the use of seeds in generating pseudorandom numbers.

### The numpy.random package

The numpy.random package is a sub package of numpy. NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.

There are four different sections to the numpy.random package
1. Simple random Data

Simple random data is used for the basic functions of the package such as generate a random integer between 1 and 10, or generate an array of 2 rows and 2 columns and fill it will random numbers between 0-1
There are assumptions based on the numbers that are generated.

2. Permutations

This section only contains two functions and they are both similar as they both shuffle or rearrange the number or numbers they are given

3. Distributions

The distributions section is the largest section of the four and they are all different probability distributions.

4. Random Generator

This section you can get the seed of the random number generator, get the state and set the state.

### Simple random data

In this section i am going to pick a few of the functions and try to explain them using plots instead of text.

-------------------------------------------------------------------------------------------------------------------------------
#### rand(d0, d1, …, dn)

In [47]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
np.random.rand(10)

array([0.79534485, 0.79631047, 0.91374177, 0.94859108, 0.26774216,
       0.77587349, 0.24378887, 0.37689705, 0.34677255, 0.36328522])

Most basic is to see what happens when we send a single value into the function, and as send above when 10 is entered it returns an array of 10 random numbers between 0-1

In [3]:
np.random.rand(2,3)

array([[0.2364483 , 0.60710296, 0.85836928],
       [0.42572109, 0.90522172, 0.24873898]])

Two input values then shows an array with two sets of arrays with three values between 0-1

In [4]:
np.random.rand(1,3,2,5)

array([[[[0.76372997, 0.33450584, 0.44535867, 0.98851168, 0.81946508],
         [0.84789585, 0.64969314, 0.18154524, 0.37938421, 0.32051849]],

        [[0.34768384, 0.39005573, 0.79503344, 0.36079146, 0.33421208],
         [0.45396405, 0.1507029 , 0.97016334, 0.56352799, 0.87657636]],

        [[0.37830904, 0.58280698, 0.89789008, 0.09440799, 0.23096865],
         [0.17098235, 0.7686225 , 0.5981287 , 0.24549247, 0.661198  ]]]])

A four input rand function shows an array with Three sets of random numbers and in each one of them sets is two more sets containing five random numbers between 0-1

In [5]:
np.random.rand(2,3,2,5)

array([[[[0.5391979 , 0.4566889 , 0.85794766, 0.84313332, 0.5080006 ],
         [0.67692443, 0.48757786, 0.93130017, 0.16312396, 0.45362253]],

        [[0.65348392, 0.69354594, 0.66141429, 0.52365875, 0.39272375],
         [0.55979759, 0.70281312, 0.46504948, 0.25742379, 0.38304389]],

        [[0.41088379, 0.55650884, 0.21204421, 0.3270768 , 0.36260123],
         [0.07858743, 0.51872415, 0.39277884, 0.88025838, 0.50491435]]],


       [[[0.58161596, 0.99895331, 0.0057144 , 0.995242  , 0.27651651],
         [0.20340317, 0.7500913 , 0.66012063, 0.88185606, 0.76206279]],

        [[0.4504051 , 0.0025888 , 0.68283212, 0.13684756, 0.58245869],
         [0.68439418, 0.88753147, 0.50937455, 0.83188987, 0.63448138]],

        [[0.50566453, 0.52470511, 0.77998304, 0.85383066, 0.92935718],
         [0.20587947, 0.28263774, 0.0309083 , 0.91514494, 0.24791909]]]])

A four input random array with similar input values apart from the first where the first value is a 2. This shows a single array with two sets of arrays that contains two sets with five random values between 0-1.

In [6]:
np.random.rand(-10)

ValueError: negative dimensions are not allowed

In [ ]:
np.random.rand(0)

In [ ]:
np.random.rand()

##### Conclusion on rand() function
From Looking at the numpy.random.rand function it appears that the last number given in the function is the amount of random numbers between 0-1 in each array, so a single number input gives that number of random numbers.
An input value of (2,3) will give two array sets with 3 random numbers in each.
An input of (3,2,1) will give three array sets each containing two array sets that each contain one random number,

A negative number gives an ValueError

An input value of 0 gives an empty array

an empty function will give an output of a single random value



-------------------------------------------------------------------------------------------------------------------------------
### numpy.random.randn(d0, d1, ..., dn)

In [11]:
np.random.randn(10)

array([ 0.2714124 ,  1.02817862, -0.37645301,  1.48750982, -0.01136357,
        0.65346616, -0.71633652, -0.87860567, -1.52269471, -0.33449908])

In [15]:
np.random.randn()

-2.2143063862577352

In [17]:
np.random.randn(3,2,1)

array([[[-0.58451375],
        [-0.44866068]],

       [[-1.47633487],
        [ 0.5848266 ]],

       [[ 0.32044102],
        [ 0.06450551]]])

In [21]:
np.random.randn(3,3,5)+4*2

array([[[ 6.19762341,  7.0444376 ,  8.68312165,  7.28498231,
         10.46605307],
        [ 9.13412516,  6.7915837 ,  9.10931148,  7.97457825,
          7.96583179],
        [ 6.01958302,  7.8278284 ,  8.74133893,  6.82072073,
          6.83753112]],

       [[ 7.67354475,  7.21877396,  8.0043565 ,  7.28785123,
          7.18626422],
        [ 8.67967339,  8.52874554,  7.04786796,  6.06906843,
          6.66577847],
        [ 7.46500383,  6.16836713,  8.82893993,  8.39186459,
          7.05018158]],

       [[ 7.28598809,  4.98715703,  8.13165666,  7.82456159,
          7.98849647],
        [ 8.10875753,  9.17003035,  8.31628244,  8.6115748 ,
          7.49737501],
        [ 7.56756234,  8.69976161,  8.71573849,  7.73686026,
          8.01930769]]])

#### Conclusion on the randn() function

From running some tests on the randn() function it is clear that it had the same functionality as the rand() function but it gives random number both positive and negative

-------------------------------------------------------------------------------------------------------------------------------
### numpy.random.randint(low, high=None, size=None, dtype='l')

In [38]:
#prints a random number between 0-10 as 10 is the max in the situation
np.random.randint(10)

7

In [34]:
#prints a random number with a low of 3 and a high of 7
np.random.randint(3,7)

5

In [39]:
#A value error is throw if the low number is greater than the high number
np.random.randint(7,4)

ValueError: low >= high

In [36]:
#prints a 3 dimensional array with a high value of 3
np.random.randint(3,size=(3,2,1))

array([[[0],
        [0]],

       [[2],
        [2]],

       [[1],
        [0]]])

In [40]:
#A three dimensional array with a low of 3 and a high of 7 so array values have to be between 3 and including 6
np.random.randint(3,7,size=(3,2,1))

array([[[6],
        [5]],

       [[4],
        [5]],

       [[6],
        [6]]])

In [45]:
np.random.randint(3,7,size=(3,2,1),dtype='i')

array([[[4],
        [3]],

       [[5],
        [5]],

       [[4],
        [6]]])

In [46]:
np.random.randint(3,7,size=(3,2,1),dtype='f')

TypeError: Unsupported dtype "float32" for randint

### Conclusion on the randint() function

Lets you pick the low and high range of values that is output, Out put shape can also be input,
the dtype can be input if you want values greater than 65535, so if you want values greater that that you can set the dtype to 'int64', 'f' will not be accepted and cause an error as that is an unsupported type float