# Programming for Data Analysis Assignment
### Assignment Outlines
The following assignment concerns the numpy.random package in Python 
1. Explain the overall purpose of the package. 
2. Explain the use of the “Simple random data” and “Permutations” functions. 
3. Explain the use and purpose of at least five “Distributions” functions. 
4. Explain the use of seeds in generating pseudorandom numbers.

### The numpy.random package

The numpy.random package is a sub package of numpy. NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.

There are four different sections to the numpy.random package
1. Simple random Data

Simple random data is used for the basic functions of the package such as generate a random integer between 1 and 10, or generate an array of 2 rows and 2 columns and fill it will random numbers between 0-1
There are assumptions based on the numbers that are generated.

2. Permutations

This section only contains two functions and they are both similar as they both shuffle or rearrange the number or numbers they are given

3. Distributions

The distributions section is the largest section of the four and they are all different probability distributions.

4. Random Generator

This section you can get the seed of the random number generator, get the state and set the state.

### Simple random data

In this section i am going to pick a few of the functions and try to explain them using plots instead of text.

#### rand(d0, d1, …, dn)

In [1]:
import numpy as np

In [2]:
np.random.rand(10)

array([0.79764663, 0.84956906, 0.1507345 , 0.70870874, 0.03305099,
       0.59259907, 0.59279715, 0.56965017, 0.62554535, 0.18676206])

Most basic is to see what happens when we send a single value into the function, and as send above when 10 is entered it returns an array of 10 random numbers between 0-1

In [24]:
np.random.rand(2,3)

array([[0.62822903, 0.79407322, 0.47819655],
       [0.76512784, 0.32075916, 0.8146097 ]])

Two input values then shows an array with two sets of arrays with three values between 0-1

In [27]:
np.random.rand(1,3,2,5)

array([[[[0.22563057, 0.21584698, 0.10705284, 0.47278658, 0.13195096],
         [0.37505734, 0.81541792, 0.19779679, 0.68532795, 0.07903537]],

        [[0.95240481, 0.02914357, 0.91868141, 0.77851443, 0.55813322],
         [0.04916274, 0.02182312, 0.53126451, 0.51045432, 0.57490704]],

        [[0.29165224, 0.22306761, 0.73177564, 0.55632974, 0.05244897],
         [0.58752321, 0.73535024, 0.90626914, 0.29732232, 0.56546374]]]])

A four input rand function shows an array with Three sets of random numbers and in each one of them sets is two more sets containing five random numbers between 0-1

In [28]:
np.random.rand(2,3,2,5)

array([[[[0.49334956, 0.17778995, 0.9085474 , 0.60626958, 0.23654062],
         [0.52792194, 0.40120835, 0.34989618, 0.50400468, 0.41704665]],

        [[0.75581986, 0.86383526, 0.11380129, 0.30254544, 0.0326243 ],
         [0.5967333 , 0.32026982, 0.87301039, 0.81868471, 0.01283648]],

        [[0.16074194, 0.26947291, 0.38355251, 0.76249163, 0.01738447],
         [0.0611847 , 0.07762236, 0.74223406, 0.584081  , 0.03390942]]],


       [[[0.85065561, 0.57980346, 0.71183755, 0.65056546, 0.4904011 ],
         [0.78716525, 0.96656903, 0.15712709, 0.29490767, 0.50975924]],

        [[0.91492949, 0.41533209, 0.10663913, 0.0926893 , 0.37097122],
         [0.45480358, 0.84297733, 0.23283761, 0.28840854, 0.14901883]],

        [[0.29948518, 0.18830043, 0.09516811, 0.75834838, 0.80563607],
         [0.40582286, 0.28117705, 0.00280242, 0.29663255, 0.14407345]]]])

A four input random array with similar input values apart from the first where the first value is a 2. This shows a single array with two sets of arrays that contains two sets with five random values between 0-1.

In [30]:
np.random.rand(-10)

ValueError: negative dimensions are not allowed

In [31]:
np.random.rand(0)

array([], dtype=float64)

In [32]:
np.random.rand()

0.42794245697521704

##### Conclusion on rand() function
From Looking at the numpy.random.rand function it appears that the last number given in the function is the amount of random numbers between 0-1 in each array, so a single number input gives that number of random numbers.
An input value of (2,3) will give two array sets with 3 random numbers in each.
An input of (3,2,1) will give three array sets each containing two array sets that each contain one random number,

A negative number gives an ValueError

An input value of 0 gives an empty array

an empty function will give an output of a single random value

